<section class="hex f-col center-x g-row-3 h-content">
  <div class="row center-x">
    <div class="col hex-card f-col f-0 g-row-1">
      <div class="row input-row">
        <div class="col selected-color center"></div>

        <div class="col center">
          <div class="row g-col-0.5">
            <div class="col input-col f-col f-0">
              <div class="row">
                <label class="col center-x" for="r">R</label>
              </div>

              <div class="row">
                <input id="r" class="col hex-input text-center" value="FF" disabled/>
              </div>
            </div>

            <div class="col input-col f-col f-0">
              <div class="row">
                <label class="col center-x" for="g">G</label>
              </div>

              <div class="row">
                <input id="g" class="col hex-input text-center" value="FF" disabled/>
              </div>
            </div>

            <div class="col input-col f-col f-0">
              <div class="row">
                <label class="col center-x" for="b">B</label>
              </div>

              <div class="row">
                <input id="b" class="col hex-input text-center" value="FF" disabled/>
              </div>
            </div>
          </div>
        </div>

        <div class="col center">
          <button type="button" class="button copy-hex g-col-0.5"><i class="fa fa-copy"></i> Copy</button>
        </div>
      </div>

      <div class="row">
        <div class="col hex-grid f-col">
          <div class="row">
            <div class="col center f-0">FF</div>
            <div class="col center f-0">FE</div>
            <div class="col center f-0">FD</div>
            <div class="col center f-0">FC</div>
            <div class="col center f-0">FB</div>
            <div class="col center f-0">FA</div>
            <div class="col center f-0">F9</div>
            <div class="col center f-0">F8</div>
            <div class="col center f-0">F7</div>
            <div class="col center f-0">F6</div>
            <div class="col center f-0">F5</div>
            <div class="col center f-0">F4</div>
            <div class="col center f-0">F3</div>
            <div class="col center f-0">F2</div>
            <div class="col center f-0">F1</div>
            <div class="col center f-0">F0</div>
          </div>
          <div class="row">
            <div class="col center f-0">EF</div>
            <div class="col center f-0">EE</div>
            <div class="col center f-0">ED</div>
            <div class="col center f-0">EC</div>
            <div class="col center f-0">EB</div>
            <div class="col center f-0">EA</div>
            <div class="col center f-0">E9</div>
            <div class="col center f-0">E8</div>
            <div class="col center f-0">E7</div>
            <div class="col center f-0">E6</div>
            <div class="col center f-0">E5</div>
            <div class="col center f-0">E4</div>
            <div class="col center f-0">E3</div>
            <div class="col center f-0">E2</div>
            <div class="col center f-0">E1</div>
            <div class="col center f-0">E0</div>
          </div>
          <div class="row">
            <div class="col center f-0">DF</div>
            <div class="col center f-0">DE</div>
            <div class="col center f-0">DD</div>
            <div class="col center f-0">DC</div>
            <div class="col center f-0">DB</div>
            <div class="col center f-0">DA</div>
            <div class="col center f-0">D9</div>
            <div class="col center f-0">D8</div>
            <div class="col center f-0">D7</div>
            <div class="col center f-0">D6</div>
            <div class="col center f-0">D5</div>
            <div class="col center f-0">D4</div>
            <div class="col center f-0">D3</div>
            <div class="col center f-0">D2</div>
            <div class="col center f-0">D1</div>
            <div class="col center f-0">D0</div>
          </div>
          <div class="row">
            <div class="col center f-0">CF</div>
            <div class="col center f-0">CE</div>
            <div class="col center f-0">CD</div>
            <div class="col center f-0">CC</div>
            <div class="col center f-0">CB</div>
            <div class="col center f-0">CA</div>
            <div class="col center f-0">C9</div>
            <div class="col center f-0">C8</div>
            <div class="col center f-0">C7</div>
            <div class="col center f-0">C6</div>
            <div class="col center f-0">C5</div>
            <div class="col center f-0">C4</div>
            <div class="col center f-0">C3</div>
            <div class="col center f-0">C2</div>
            <div class="col center f-0">C1</div>
            <div class="col center f-0">C0</div>
          </div>
          <div class="row">
            <div class="col center f-0">BF</div>
            <div class="col center f-0">BE</div>
            <div class="col center f-0">BD</div>
            <div class="col center f-0">BC</div>
            <div class="col center f-0">BB</div>
            <div class="col center f-0">BA</div>
            <div class="col center f-0">B9</div>
            <div class="col center f-0">B8</div>
            <div class="col center f-0">B7</div>
            <div class="col center f-0">B6</div>
            <div class="col center f-0">B5</div>
            <div class="col center f-0">B4</div>
            <div class="col center f-0">B3</div>
            <div class="col center f-0">B2</div>
            <div class="col center f-0">B1</div>
            <div class="col center f-0">B0</div>
          </div>
          <div class="row">
            <div class="col center f-0">AF</div>
            <div class="col center f-0">AE</div>
            <div class="col center f-0">AD</div>
            <div class="col center f-0">AC</div>
            <div class="col center f-0">AB</div>
            <div class="col center f-0">AA</div>
            <div class="col center f-0">A9</div>
            <div class="col center f-0">A8</div>
            <div class="col center f-0">A7</div>
            <div class="col center f-0">A6</div>
            <div class="col center f-0">A5</div>
            <div class="col center f-0">A4</div>
            <div class="col center f-0">A3</div>
            <div class="col center f-0">A2</div>
            <div class="col center f-0">A1</div>
            <div class="col center f-0">A0</div>
          </div>
          <div class="row">
            <div class="col center f-0">9F</div>
            <div class="col center f-0">9E</div>
            <div class="col center f-0">9D</div>
            <div class="col center f-0">9C</div>
            <div class="col center f-0">9B</div>
            <div class="col center f-0">9A</div>
            <div class="col center f-0">99</div>
            <div class="col center f-0">98</div>
            <div class="col center f-0">97</div>
            <div class="col center f-0">96</div>
            <div class="col center f-0">95</div>
            <div class="col center f-0">94</div>
            <div class="col center f-0">93</div>
            <div class="col center f-0">92</div>
            <div class="col center f-0">91</div>
            <div class="col center f-0">90</div>
          </div>
          <div class="row">
            <div class="col center f-0">8F</div>
            <div class="col center f-0">8E</div>
            <div class="col center f-0">8D</div>
            <div class="col center f-0">8C</div>
            <div class="col center f-0">8B</div>
            <div class="col center f-0">8A</div>
            <div class="col center f-0">89</div>
            <div class="col center f-0">88</div>
            <div class="col center f-0">87</div>
            <div class="col center f-0">86</div>
            <div class="col center f-0">85</div>
            <div class="col center f-0">84</div>
            <div class="col center f-0">83</div>
            <div class="col center f-0">82</div>
            <div class="col center f-0">81</div>
            <div class="col center f-0">80</div>
          </div>
          <div class="row">
            <div class="col center f-0">7F</div>
            <div class="col center f-0">7E</div>
            <div class="col center f-0">7D</div>
            <div class="col center f-0">7C</div>
            <div class="col center f-0">7B</div>
            <div class="col center f-0">7A</div>
            <div class="col center f-0">79</div>
            <div class="col center f-0">78</div>
            <div class="col center f-0">77</div>
            <div class="col center f-0">76</div>
            <div class="col center f-0">75</div>
            <div class="col center f-0">74</div>
            <div class="col center f-0">73</div>
            <div class="col center f-0">72</div>
            <div class="col center f-0">71</div>
            <div class="col center f-0">70</div>
          </div>
          <div class="row">
            <div class="col center f-0">6F</div>
            <div class="col center f-0">6E</div>
            <div class="col center f-0">6D</div>
            <div class="col center f-0">6C</div>
            <div class="col center f-0">6B</div>
            <div class="col center f-0">6A</div>
            <div class="col center f-0">69</div>
            <div class="col center f-0">68</div>
            <div class="col center f-0">67</div>
            <div class="col center f-0">66</div>
            <div class="col center f-0">65</div>
            <div class="col center f-0">64</div>
            <div class="col center f-0">63</div>
            <div class="col center f-0">62</div>
            <div class="col center f-0">61</div>
            <div class="col center f-0">60</div>
          </div>
          <div class="row">
            <div class="col center f-0">5F</div>
            <div class="col center f-0">5E</div>
            <div class="col center f-0">5D</div>
            <div class="col center f-0">5C</div>
            <div class="col center f-0">5B</div>
            <div class="col center f-0">5A</div>
            <div class="col center f-0">59</div>
            <div class="col center f-0">58</div>
            <div class="col center f-0">57</div>
            <div class="col center f-0">56</div>
            <div class="col center f-0">55</div>
            <div class="col center f-0">54</div>
            <div class="col center f-0">53</div>
            <div class="col center f-0">52</div>
            <div class="col center f-0">51</div>
            <div class="col center f-0">50</div>
          </div>
          <div class="row">
            <div class="col center f-0">4F</div>
            <div class="col center f-0">4E</div>
            <div class="col center f-0">4D</div>
            <div class="col center f-0">4C</div>
            <div class="col center f-0">4B</div>
            <div class="col center f-0">4A</div>
            <div class="col center f-0">49</div>
            <div class="col center f-0">48</div>
            <div class="col center f-0">47</div>
            <div class="col center f-0">46</div>
            <div class="col center f-0">45</div>
            <div class="col center f-0">44</div>
            <div class="col center f-0">43</div>
            <div class="col center f-0">42</div>
            <div class="col center f-0">41</div>
            <div class="col center f-0">40</div>
          </div>
          <div class="row">
            <div class="col center f-0">3F</div>
            <div class="col center f-0">3E</div>
            <div class="col center f-0">3D</div>
            <div class="col center f-0">3C</div>
            <div class="col center f-0">3B</div>
            <div class="col center f-0">3A</div>
            <div class="col center f-0">39</div>
            <div class="col center f-0">38</div>
            <div class="col center f-0">37</div>
            <div class="col center f-0">36</div>
            <div class="col center f-0">35</div>
            <div class="col center f-0">34</div>
            <div class="col center f-0">33</div>
            <div class="col center f-0">32</div>
            <div class="col center f-0">31</div>
            <div class="col center f-0">30</div>
          </div>
          <div class="row">
            <div class="col center f-0">2F</div>
            <div class="col center f-0">2E</div>
            <div class="col center f-0">2D</div>
            <div class="col center f-0">2C</div>
            <div class="col center f-0">2B</div>
            <div class="col center f-0">2A</div>
            <div class="col center f-0">29</div>
            <div class="col center f-0">28</div>
            <div class="col center f-0">27</div>
            <div class="col center f-0">26</div>
            <div class="col center f-0">25</div>
            <div class="col center f-0">24</div>
            <div class="col center f-0">23</div>
            <div class="col center f-0">22</div>
            <div class="col center f-0">21</div>
            <div class="col center f-0">20</div>
          </div>
          <div class="row">
            <div class="col center f-0">1F</div>
            <div class="col center f-0">1E</div>
            <div class="col center f-0">1D</div>
            <div class="col center f-0">1C</div>
            <div class="col center f-0">1B</div>
            <div class="col center f-0">1A</div>
            <div class="col center f-0">19</div>
            <div class="col center f-0">18</div>
            <div class="col center f-0">17</div>
            <div class="col center f-0">16</div>
            <div class="col center f-0">15</div>
            <div class="col center f-0">14</div>
            <div class="col center f-0">13</div>
            <div class="col center f-0">12</div>
            <div class="col center f-0">11</div>
            <div class="col center f-0">10</div>
          </div>
          <div class="row">
            <div class="col center f-0">0F</div>
            <div class="col center f-0">0E</div>
            <div class="col center f-0">0D</div>
            <div class="col center f-0">0C</div>
            <div class="col center f-0">0B</div>
            <div class="col center f-0">0A</div>
            <div class="col center f-0">09</div>
            <div class="col center f-0">08</div>
            <div class="col center f-0">07</div>
            <div class="col center f-0">06</div>
            <div class="col center f-0">05</div>
            <div class="col center f-0">04</div>
            <div class="col center f-0">03</div>
            <div class="col center f-0">02</div>
            <div class="col center f-0">01</div>
            <div class="col center f-0">00</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
