<?php

use app\Models\Url;

?>

<section class="home f-col center-x g-row-3 h-content">
  <div class="row center-x g-2">
    <a class="col card center-y" href="<?= Url::to('hex') ?>" aria-label="Link to the hex tool">
      <div class="row g-col-2">
        <div class="col card-icon center f-0">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </div>

        <div class="col f-col g-row-1">
          <div class="row">
            <div class="col">
              <h2 class="card-title" data-typo="h4">Hex</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p>A tool to easily get and view hexadecimal color codes.</p>
            </div>
          </div>
        </div>
      </div>
    </a>

    <a class="col card center-y" href="<?= Url::to('hex') ?>" aria-label="Link to the hex tool" inert>
      <div class="row g-col-2">
        <div class="col card-icon center f-0">
          <i class="fas fa-wrench" aria-hidden="true"></i>
        </div>

        <div class="col f-col g-row-1">
          <div class="row">
            <div class="col">
              <h2 class="card-title" data-typo="h4">Work in Progress</h2>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <p>More tools coming soon!</p>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>
</section>
