<?php

use app\Models\Url;

?>

<header>
  <div class="row navbar g-col-1">
    <nav class="col menu between-x">
      <div class="row nav-list w-auto f-0">
        <a class="col nav-item link center f-0" href="<?= Url::to(REDIRECT) ?>" aria-label="Link to <?= REDIRECT ?> page">
          <span class="center h-100"><i class="fa fa-home"></i> <?= ucfirst(REDIRECT) ?></span>
        </a>

        <a class="col nav-item link center f-0" href="<?= Url::to('hex') ?>" aria-label="Link to the hex tool">
          <span class="center h-100"><i class="fa fa-palette"></i> Hex</span>
        </a>
      </div>
    </nav>

    <div class="col nav-options">
      <div class="row end-x h-100">
        <div class="col theme-switch center f-0"></div>

        <button class="col hamburger hamburger--squeeze f-0" type="button" aria-label="Toggle navigation menu" aria-controls="navigation" aria-expanded="false" tabindex="1">
          <span class="hamburger-box center">
            <span class="hamburger-inner"></span>
          </span>
        </button>
      </div>
    </div>
  </div>
</header>
